name: CI
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v7
    - name: setup
      uses: actions/setup-java@v6
      with:
        java-version: '25'
        distribution: temurin
        cache: maven
    - name: test
      run: ./mvnw --batch-mode test
